go-pkgz/auth

provider/dev_provider.go
=> Dev Auth layout

auth.go
Right now Yandex Open Auth can not be enabled, due to the fact that it is replaced with the `NewFacebook` Open Auth instance. I thought this wasn't intentional because `NewYandex` struct exists in a corresponding source file.
Yet again I wasn't able to provide additional test-cases. But I ran existing tests (with exception of coveralls) successfully.
=> Enable Yandex Open Auth

token/jwt.go
The latest [commit](https://github.com/go-pkgz/auth/commit/2db2238aa8ff296a23d29eb300955bdb866bbd32) effectively does nothing because `e` is a pointer.
=> Claims validation - preserve orginal error

provider/dev_provider.go, provider/oauth2.go, provider/oauth2_test.go, provider/providers.go, provider/service.go
To resolve #7 
login/logout/callback url is always formed (and hardcoded) as:
ROOT_URL/{router path}/PROVIDER/{login | callback | logout}
Would it make sense to define redirect URL in Oauth2Handler Login method in runtime as:
p.conf.RedirectURL = p.URL + r.URL.Path + "/callback" ?
=> Proposed changes to address: /auth prefix hardcoded in providers

README.md, _example/go.sum, _example/main.go, auth.go, go.mod, go.sum, provider/oauth1.go, provider/oauth1_test.go, provider/providers.go, provider/providers_test.go
=> Support twitter auth 

middleware/auth.go
To avoid [timing attack](https://en.wikipedia.org/wiki/Timing_attack)
=> Using ConstantTimeCompare instead of regular string comparison

.github/workflows/ci.yml, avatar/gridfs_test.go, avatar/store_test.go
`MONGO_TEST` variable in CI was unused and a single local test without mongo was failing. This PR fixes that.
=> Fix local tests in case of MONGO_TEST env variable absence

.golangci.yml, README.md, _example/frontend/index.html, _example/main.go, auth.go, auth_test.go, avatar/avatar.go, avatar/avatar_test.go, go.mod, provider/direct.go, provider/oauth1.go, provider/oauth2.go, provider/oauth2_test.go, provider/providers.go, provider/service.go, provider/service_test.go, provider/verify.go, provider/verify_test.go
Implements azure aouth2. Handles basic user info as well as a separate authorized call required by azure to retrieve avatar. 
Note: the call hits beta API because production one is not supported yet, see https://github.com/microsoftgraph/microsoft-graph-docs/issues/3990
#55
=> Microsoft (azure) oauth2 provider

README.md, provider/direct.go, provider/direct_test.go
In some case it's required to send user provided input data in POST request. This PR adds `application/x-www-form-urlencoded` and `application/json` encoded body processors to the direct handler.
=> Add a POST request handler to the direct provider

README.md, middleware/auth.go, middleware/auth_test.go, token/user.go
- `auth.RBAC` method for handlers
- developers can set optional roles in claims updater `claims.User.SetRole`
Not using attributes to store roles to maintain backward compatibility so that it won't break for anyone whole already have a `role` key in attributes.
=> Simple Role Based access control

README.md, middleware/auth.go, middleware/auth_test.go, middleware/user_updater.go
Converted RBAC middleware to a more traditional signature and added support of matching against multiple roles.
The reason for this change - in any modern framework supporting middleware chains (i.e. route.With(middleware, middleware2, ....) the old signature expecting handler as a part of the call is not smth usual and not easy to use. In addition, in practical use cases, one route (or group of routes) often allowed for multiple roles.
Another thing included in this PR - old test with ClaimUpdater counted on token's refresh and didn't work in normal circumstances. I'm not really sure how it even passed Actions CI, probably due to incorrect (different) clock on action workers. Replaced by pre-generated token and simplified test's code.
@kleash pls take a look. This change won't be …
=> RBAC with multiple roles and chains-friendly

auth.go, auth_test.go, token/jwt.go, token/jwt_test.go
=> allow header-only login (response) with SendJWTHeader param

avatar/avatar.go, avatar/avatar_test.go, avatar/noop_test.go
this seems to be a little bit over paranoid, but the goal is to address "Uncontrolled data used in path expression" reported by codeql
Currently, we get the last element of the request's path as a file name and this unlikely may be used to access something unexpected. Either way, the change is adding strict verification of that element to make sure the request matches the allowed pattern for a valid image - `^[a-fA-F0-9]{40}\.image$`
=> verify avatar pattern from requests

provider/oauth2.go, provider/oauth2_test.go, token/jwt.go
with all the paranoid measures we still force involuntary exposure of user's avatar. On the service level, this can be disabled with the claim's updater, but there is no user-level solution.
This PR adds support of an optional "noava" param to the login query. In this case, the real avatar from the oauth2 provider will be dropped and an automatic (identicoin) avatar will be used instead. Flipping thins logic (i.e. dropping avatar by default) will be even better, but it may break back-compatibility.
=> add support of noava query param for oauth2

README.md, _example/main.go, auth.go, auth_test.go, provider/apple.go, provider/apple_pubkeys.go, provider/apple_pubkeys_test.go, provider/apple_test.go, provider/oauth2_test.go
Implementation of `Sign in with Apple`  #61
Apple API has some limit for implement full features compatible with the package:
1. Apple hasn't API for fetch avatar. If any one know how to do it let me know (also no `userInfo` api).
2. Fetch user name (if set in scope) possible only one, at first user login with a service. With next login  `userName` field doesn't exist in API response, until user will delete sign with an app in account profile (security section).
I will planning update the `Readme` after code review.
Waiting for your comments
=> added sign in with apple

provider/apple.go
Defer func with `Body.Close()` called after an error check. If an error occurred `defer` never called and file descriptors could been leaking. I moved `defer` block above error check for fix that.
=> Fixed bug with body close at Apple provider

provider/apple.go, provider/telegram.go, provider/telegram_test.go
Likely solves #92. Btw we don't have any tests for cookies in telegram auth.
=> Add Audience, ExpiresAt and NotBefore to telegram JWT token

.github/workflows/ci.yml, .golangci.yml, auth.go, auth_test.go, provider/apple.go, provider/direct.go, provider/direct_test.go
The direct provider uses just the name (hashed) to make a user ID. In many cases this is exactly what is needed, i.e. login with user/passwd may expect unique user names, however in some tricky cases we may want to change the default behavior. For example, the implementation of an anonymous provider, where no password is even passed and uniqueness on the name can not be expected.
The PR adds support of `UserIDFunc` overriding a part of the id. The prefix (provider name) still mandated but the rest can be whatever user like. It accepts both name and http.Request params, so it is possible to generate id based on the user name and mix in some ip parts.
I'm not sure if we should enforce hashing of `UserIDFunc` result or left it to the caller
=> Direct with custom user id func

provider/providers.go
The tenant for microsoft.AzureADEndpoint is currently "consumers".  As per
the
[documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints),
this allows only users with personal Microsoft accounts (MSA) to sign
into the application.  Change it to "common" in order to allow users
with both personal Microsoft accounts and work/school accounts from
Azure AD to sign into the application.
Fixes #106
=> support both personal and work/school Microsoft accounts

_example/main.go
The check below fails in _example because in auth options URL defined as `http://localhost:8080`.  It should match. 
https://github.com/go-oauth2/oauth2/blob/c121ece09e9d992ed7c2e5eda4b2cd3120b9ad6e/manage/util.go#L16
#29
=> fix _example with CustomProvider on go-auth2/oauth2 server

provider/custom_server.go, provider/dev_provider.go, provider/verify.go, provider/verify_test.go
this PR sanitizes both user and address prior to confirmation callback.
This was done to prevent untrusted user input to set those fields (mostly user) to something we may send, for example, as an email. I'm not sure if an email's HTML can be attacked with injected JS, but either way, it prevents malicious attempts to make fake emails with rich content
@paskal - this is the provider you are familiar with and we usually use it for email logins. Pls take a look
=> sanitize both user and address in verified provider

avatar/store.go, provider/telegram.go, provider/telegram_moq_test.go
Mockery-generated mock was never used in the current code.
=> Remove unused mockery call, regenerate moq

avatar/store.go
30s is the default:
https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.serverSelectionTimeoutMS
Resolves #127
=> Support mongodb+srv:// in image store, increase timeout on 30s

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .golangci.yml, auth_test.go, avatar/avatar_test.go, avatar/bolt_test.go, avatar/gridfs.go, avatar/gridfs_test.go, avatar/localfs_test.go, avatar/store_test.go, provider/apple_pubkeys_test.go, provider/apple_test.go, provider/custom_server.go, provider/custom_server_test.go, provider/dev_provider.go, provider/dev_provider_test.go, provider/oauth1_test.go, provider/oauth2_test.go, token/jwt_test.go, token/user_test.go
ioutil is a deprecated module, and `assert.NoError` makes test error messages formatting more clear.
Also, bump golangci-lint and fix the error `G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server`
=> Use assert.NoError in place of Nil, remove ioutil usage, bump golangci-lint

provider/apple.go, provider/apple_test.go
Previously a panic was generated with wrong key type:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```
=> Don't panic on wrong Apple private key type

auth.go
It happens when `err=nil` and `claims.User=nil` in Handlers() func.
https://github.com/go-pkgz/auth/blob/master/auth.go#L184
=> Fix nil ptr panic in auth.go

_example/README.md, provider/custom_server.go, provider/dev_provider.go
Previously the form escaped the return URL twice, preventing it from working.
Resolves #130.
=> Fix custom server return URL decoding

provider/custom_server.go, provider/oauth2.go, provider/oauth2_test.go
#123 
An example for the issue
=> Pass bearer token

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .golangci.yml, auth_test.go, avatar/avatar.go, avatar/noop.go, middleware/auth_test.go, provider/direct.go, provider/direct_test.go, provider/oauth2_test.go, provider/service_test.go, provider/telegram.go, provider/verify.go, provider/verify_test.go, token/user_test.go
Currently, the pipelines are timing out and update might help fix it.
=> Bump golangci-lint

avatar/avatar.go
Fixed two bugs:
1. According to [gravatar docs](https://en.gravatar.com/site/implement/images/) must be used trimmed and lower case email for url generation;
2. File-type extension doesn't work nowadays, so must use default file format (png).
File-type extension examples:
* good url (without file ext): https://www.gravatar.com/avatar/a443dd413b286902c47da02fe0a56e5e?d=404&s=80
* broken url (with file ext): https://www.gravatar.com/avatar/a443dd413b286902c47da02fe0a56e5e.jpg?d=404&s=80
=> Fixed wrong gravatar url generation (lower case, file type)

avatar/avatar.go
Avatar image from gravatar must be updated on each user's login. But sometime it doesn't work. After research found a possible problem:
- Current timeout for gravatar: 1 second. It's too low;
- Current download times for gravatar images by API: 0.9 - 1.2 second.
PR increases a timeout from 1 to 5 seconds, so that must fix the problem.
=> Fixed that gravatar doesn't updated at login sometimes

provider/telegram_test.go
The reason is likely slow work of goroutines due to limited CPU.
=> Fix TestTelegramConfirmedRequest failing in GitHub Actions

README.md
Update based on my experience going through them.
=> Update Google auth setup instructions

middleware/auth.go, middleware/auth_test.go
In case the token (via cookie or header) was made with the provider, what is not enabled anymore, reject this token right away
This should address https://github.com/umputun/remark42/issues/1660
=> check if user's provider is in the list of current providers

auth.go, provider/oauth2.go, provider/providers.go
Hi, 
I added the possibility to get additional customer information (instead of just username, avatar and id).
Use case:
I use this library in my project and want to simplify user authorization as much as possible. My application is require to have at least email to proceed of using full functionality of application, and I don't see any reason to limit it if customer already provide it in one of the providers and authorize to use this data in application. 
Backward compatibility
The solution is backward compatible. I saw that library still not released and we can legally broke contracts, but to avoid additional work for customers I didn't change API, just add new public method to use. 
All additional fields will go under attributes section. Example: 
```
{
"name":"Volodymyr Zaiets", …
```
=> Add possibility to get additional user data (additional scope)

README.md, go.mod, go.sum, provider/sender/email.go, provider/sender/email_test.go
@umputun @paskal Please review if you are OK with `go.mod` changes. perhaps a new release of `email` lib is required.
Also could you advise how to update `email` and `auth` libs properly in remark42 app, is it just a copy over?
=> TLS InsecureSkipVerify option

auth_test.go, token/jwt.go, v2/auth_test.go, v2/token/jwt.go
During "LogOut", JwtService.Reset() doesn't set "content-type" header that leads to "XML Parsing Error: no root element found" in FireFox.
This PR simply adds proper header.
=> Set proper "content-type" while calling JwtService.Reset()

auth.go, auth_test.go, v2/auth.go, v2/auth_test.go
There was one minor problem related to the dev and Apple providers registration.
Now it is possible to have a configuration,
where only one single dev provider is enabled.
Providers were not registered into `Service.authMiddleware.Providers` slice in the `Service.AddDevProvider()` and `Service.AddAppleProvider()` methods before.
This worked before, because other providers were registered at the same time, and `authMiddleware.Providers` slice was reassigned by other methods.
=> Fix registration of dev provider in Service.authMiddleware.Providers

README.md, auth.go, token/jwt.go, token/jwt_test.go
I discovered while using this library that the current XSRF protections do not allow for a GET request sent by the browser on protected routes, due to requiring the presence of the XSRF token in a header. This is a problem for applications that are not SPAs and send GET requests to the server to retrieve a new HTML page. In these situations, the common pattern is to skip XSRF checks on GET requests.
To resolve this, I implemented a configuration option called `XSRFIgnoreMethods`, allowing the user to specify a comma-separated list of HTTP methods for which XSRF checks should be skipped when extracting and validating the JWT. I am open to any feedback, modifications, or  discussions about this.
=> Implement XSRFIgnoreMethods

v2/auth.go, v2/token/jwt.go, v2/token/jwt_test.go
Implemented IgnoreXSRFMethods option for v2.
This contains the same changes as https://github.com/go-pkgz/auth/pull/207 for the v2 folder.
=> Implement IgnoreXSRFMethods for v2

auth_test.go, token/jwt.go, v2/auth_test.go, v2/token/jwt.go
No text is returned so the response is not a valid JSON.
Fix for header introduced in https://github.com/go-pkgz/auth/pull/203, resolves https://github.com/umputun/remark42/issues/1812. I verified the fix locally.
=> Fix Content-Type at /logout endpoint

avatar/avatar.go, avatar/avatar_test.go, avatar/noop_test.go, v2/avatar/avatar.go, v2/avatar/avatar_test.go, v2/avatar/noop_test.go
Detect proper avatar type to return instead of returning `image/*`, which is not valid.
Remark42 , before:
```
~ ❯ make rundev
~ ❯ curl -sI -X GET http://127.0.0.1:8083/api/v1/avatar/02625d3d98771929a8a6b1ff4c30628d66389ad6.image | grep Content-Type
Content-Type: image/*
```
Remark42, after:
```
~ ❯ cd backend
~ ❯ go get github.com/go-pkgz/auth@23da433 ; go mod vendor
go: downloading github.com/go-pkgz/auth v1.24.2-0.20240921020949-23da433bf4bb
go: upgraded github.com/go-pkgz/auth v1.24.2-0.20240921014908-825b117d9ed9 => v1.24.2-0.20240921020949-23da433bf4bb
~ ❯ cd ..
~ ❯ make rundev
~ ❯ curl -sI -X GET http://127.0.0.1:8083/api/v1/avatar/02625d3d98771929a8a6b1ff4c30628d66389ad6.image | grep Content-Type
Content-Type: image/png
```
=> Detect and set proper Content-Type for avatars

README.md
Since the variable names are already included in the function declaration, golang will throw an error:
```
no new variables on left side of :=
```
=> Remove extra colon in Direct Authentication example

README.md, _example/frontend/index.html, _example/main.go, auth.go, auth_test.go, provider/providers.go, provider/providers_test.go, v2/auth.go, v2/auth_test.go, v2/provider/providers.go, v2/provider/providers_test.go
Added login support for Discord. If this is approved and merged, I would like to add ~~it's~~ its support to Remark42 (love that service).
A request: Since I am currently participating in Hacktoberfest, if this PR is to be merged, kindly add the label `hacktoberfest-accepted` to it. Many thanks!
=> feature: Discord OAuth2 Provider

.golangci.yml, auth.go, auth_test.go, middleware/auth.go, middleware/auth_test.go, provider/apple.go, provider/direct.go, provider/oauth1.go, provider/oauth2.go, provider/telegram.go, provider/verify.go, token/jwt.go, v2/auth.go, v2/auth_test.go, v2/middleware/auth.go, v2/middleware/auth_test.go, v2/provider/apple.go, v2/provider/direct.go, v2/provider/oauth1.go, v2/provider/oauth2.go, v2/provider/telegram.go, v2/provider/verify.go, v2/token/jwt.go
The problem occurs when the provider name contains underscore characters `_`.
If provider name is like `provider_prod` and full `claims.User.ID`  in the JWT token looks like `provider_prod_user1`,
then [Authenticator.isProviderAllowed()](https://github.com/go-pkgz/auth/blob/master/v2/middleware/auth.go#L156-L167) check fails and provider with such name cannot be used.
This was initially discovered in  https://github.com/go-pkgz/auth/pull/201#discussion_r1624361335.
It might be better to add an explicit provider name into the JWT token claims,
and avoid parsing already serialized string back to tokens.
Provider name passed into `Service.AddProvider()`  also becomes a part of  `https://host:port/auth/provider_prod/login`  URL, and therefore it requires special handling. 
One solution is to …
=> Improve provider name handling
