go-pkgz/auth

_example/frontend/index.html, _example/frontend/main.js, _example/frontend/style.css
Fix for #8 
Fix a bit hacky, because there is no way to send headers with an iframe. Have to make ajax call, then create object URL from received data and set url of an iframe to said object URL.
=> fix iframe xsrf header missing

_example/frontend/main.js, _example/frontend/style.css
Frontend side of anonymous login support in example.
=> Add support for anonymous login in example

token/jwt_test.go
Currently test success depends on local timezone:
```
$ go test github.com/go-pkgz/auth/token
--- FAIL: TestJWT_Token (0.00s)
jwt_test.go:71: 
Error Trace:	jwt_test.go:71
Error:      	Not equal: 
expected: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0ZXN0X3N5cyIsImV4cCI6Mjc4OTE5MTgyMiwianRpIjoicmFuZG9tIGlkIiwiaXNzIjoicmVtYXJrNDIiLCJuYmYiOjE1MjY4ODQyMjIsInVzZXIiOnsibmFtZSI6Im5hbWUxIiwiaWQiOiJpZDEiLCJwaWN0dXJlIjoiaHR0cDovL2V4YW1wbGUuY29tL3BpYy5wbmciLCJpcCI6IjEyNy4wLjAuMSIsImVtYWlsIjoibWVAZXhhbXBsZS5jb20iLCJhdHRycyI6eyJib29sYSI6dHJ1ZSwic3RyYSI6InN0cmEtdmFsIn19LCJoYW5kc2hha2UiOnsic3RhdGUiOiIxMjM0NTYiLCJmcm9tIjoiZnJvbSIsImlkIjoibXlpZC0xMjM0NTYifX0._2X1cAEoxjLA7XuN8xW8V9r7rYfP_m9lSRz_9_UFzac"
actual  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0ZXN0X3N5cyIsImV4cCI6Mjc4OTE1OTQyMiwianR …
```
=> Fix tests dependence from local timezone

_example/frontend/index.html, _example/frontend/main.js, _example/frontend/style.css
=> Add email login support

README.md, provider/custom_server.go
I added more information to custom provider methods in README.
=> Add documentation to custom provider methods

README.md, avatar/bolt.go, avatar/gridfs.go, avatar/localfs.go, avatar/store.go, avatar/store_test.go
Adds support of universal avatar store uris with `file://`, `bolt://` and `mongo://` protocols
=> Avatar factory

avatar/store.go
hope that it's not a defined type
=> fix typo - double "and" in comment

provider/sender/email.go
The counterpart for umputun/remark42/pull/682 and umputun/remark42/pull/681 discovered and fixed by @ttys3.
=> Fix smtp.NewClient call params and quotedprintable flush

README.md, _example/main.go
Also fix obsolete paths to example
=> Example: according to doc string /private_data returns json with user info

README.md, _example/main.go, middleware/userUpdater.go, middleware/userUpdater_test.go
=> Adding middleware to modify UserInfo in request context

README.md, _example/frontend/index.html, auth.go, auth_test.go, provider/providers.go
Adds Battle.net login support.
[Battle.net OAuth2 doc](https://develop.battle.net/documentation/guides/using-oauth)
Made it work with my fork of https://github.com/umputun/remark42, screenshot:
=> Add Battle.net auth

README.md, auth.go, auth_test.go
=> add public method to append self-implemented handler to stack of handlers

provider/direct.go
fixes the issue with broken GET request (in some browsers?) caused by  #57
=> Fix direct GET auth

auth.go, token/jwt.go
=> support same site attribute #73

provider/telegram.go, provider/telegram_test.go
=> Prevent runtime panic in case telegram is not initialised

provider/telegram.go, provider/telegram_test.go
- sync code style with remark42
- improve parseError returned error description
- handle empty response case in BotInfo
- remove unused fields from botInfo object
- remove the unnecessary returned error from Run
- separate cleanup and processUpdates tickers
- increase processUpdates ticker from 1s to 5s
- set expired requests cleanup ticker to 5m
- increase test coverage
=> Multiple improvements to telegram auth

provider/telegram.go, provider/telegram_test.go
Previously, loop listening for new Telegram bot messages through API updates had to be run within auth, after that change it would be possible to run ProcessUpdate instead to process updates from the loop running elsewhere.
Also, do not send an error response to the person sending the request in case it doesn't start with /start, e.g. for the regular message: new behavior is to just ignore them.
Required for https://github.com/umputun/remark42/pull/1160
=> [telegram] add the ability to process updates from the third source

provider/telegram.go, provider/telegram_test.go
In Remark42, telegram auth used with its own API updates listener and TelegramHandler.Run is never called, which currently leaves TelegramHandler.username unset and returned empty when Telegram login attempt is made.
This PR changes that, so that username will be always set or error will be returned otherwise.
=> [telegram] return telegram bot username when Run is not used

auth.go, avatar/avatar.go, avatar/avatar_test.go, avatar/bolt.go, avatar/gridfs.go, avatar/localfs.go, avatar/localfs_test.go, avatar/store.go, avatar/store_test.go, go.mod, logger/interface_test.go, middleware/auth.go, middleware/auth_test.go, provider/apple.go, provider/apple_pubkeys.go, provider/apple_pubkeys_test.go, provider/apple_test.go, provider/direct.go, provider/direct_test.go, provider/sender/email.go, provider/sender/email_test.go, provider/service.go, provider/service_test.go, provider/telegram.go, provider/verify.go, provider/verify_test.go, token/jwt.go, token/jwt_test.go, token/user.go, token/user_test.go
https://gist.github.com/Peltoche/60b8b81dfbf70164d0e2b88988003229 was used for it, thanks to @Peltoche for publishing it.
I've reviewed each changed line manually and changed all wraps without checking for errors not equal to nil to have that check and return plain nil otherwise.
=> Get rid of errors package in favour of fmt

README.md
=> Added hyperlink to "query strings are not secure"

avatar/bolt_test.go, avatar/gridfs.go, avatar/gridfs_test.go, avatar/localfs.go, avatar/noop_test.go
It was already the case but never checked.
=> Verify that Close() calls are idempotent

README.md
See https://github.com/umputun/remark42/pull/1806
=> docs: Update Apple Auth Provider section of README

README.md, _example/go.mod, _example/go.sum, _example/main.go
Migrate example to v2, add it to Readme
Resolves #221.
=> Release v2

README.md
I think the Details links were a bit confusing to me
=> update README links to v2 and fix line numbers
